### ISSUE TITLE
Incorrect Github URL on website

### ISSUE THREAD

**Issue by bitcrafty** [RetroMusicPlayer/retromusicplayer.github.io#12]
The github URL for a developer on the website is incorrect. It shows an error when clicked on it.
Its because the url is missing an additional slash ("/") in the html file. (on line 88 in the [about](https://github.com/RetroMusicPlayer/retromusicplayer.github.io/blob/main/about.html) file.)

<img align="left" height="400" src="https://github.com/RetroMusicPlayer/retromusicplayer.github.io/assets/135437223/c3795dd2-0062-4e65-b863-7d7d555a78c4">
<img  width="520" src="https://github.com/RetroMusicPlayer/retromusicplayer.github.io/assets/135437223/fe007ebc-8d24-4c15-8afe-f6b06e0340a6">

**Comment by Daksh777** [comment]
Really sorry for the delay and thank you so much for opening the issue @bitcrafty!
Would you like to make a PR to fix the error or should I do it?

**Comment by bitcrafty** [comment]
I will make a PR and submit it. 👍
Will get some github activity that way 😂😅
